
source "https://rubygems.org"

# ruby "2.0.0", :engine => "jruby", :engine_version => "1.7.11"
# ruby "1.9.3", :engine => "jruby", :engine_version => "1.7.11"
# ruby '1.9.3'
# ruby '2.1.2'
# ruby '2.1.3'
# ruby '2.2.0'
ruby '2.2.2'

#gem 'activerecord'
#gem 'activesupport'
gem 'addressable'
#gem 'awesome_print'
#gem 'bcrypt'
#gem 'bluecloth'
#gem 'celes'
gem 'coderay'
#gem 'config'
#gem 'crack'
#gem 'daemons'
#gem 'dm-core'
#gem 'dm-migrations'
#gem 'dm-sqlite-adapter'
#gem 'dotenv'
#gem 'erubis'
gem 'equationoftime', 
    :git => 'https://github.com/DouglasAllen/equationoftime.git',
    :require => 'eot'
#gem 'execjs'
#gem 'faker'
#gem 'flowdock'
#gem 'guard'
gem 'haml'
#gem 'httparty'
#gem 'http_router'
#gem 'json'
#gem 'json_pure'
#gem 'jquery'
#gem 'kramdown'
#gem 'liquid'
#gem 'logger'
#gem 'maruku'
#gem 'multi_xml'
#gem 'nokogiri'
#gem 'omniauth-github'
#gem 'pg'
gem 'pry-byebug'
#gem 'pygments'
gem 'rygments'
gem 'rack-codehighlighter', :require => 'rack/codehighlighter'
gem 'rdiscount'
#gem 'RedCloth'
#gem 'rest-client'
#gem 'safe_yaml'
#gem 'sass'
gem 'shotgun'
gem 'sinatra'
#gem 'sinatra-activerecord'
gem 'sinatra-contrib'
#gem 'sinatra-flash'
#gem 'sqlite3'
#gem 'terminal-notifier-guard'
#gem 'textacular'
#gem 'therubyracer'
gem 'thin'
gem 'uv'
