source "http://rubygems.org"

# ruby "2.0.0", :engine => "jruby", :engine_version => "1.7.11"
# ruby "1.9.3", :engine => "jruby", :engine_version => "1.7.11"
# ruby '1.9.3'
# ruby '2.1.2'
# ruby '2.1.3'
# ruby '2.2.0'
ruby '2.2.2'

gem 'addressable', :git => 'https://github.com/DouglasAllen/addressable.git'
gem 'backports', :git => 'https://github.com/DouglasAllen/backports.git'
gem 'bundler', :git => 'https://github.com/DouglasAllen/bundler.git'
#gem 'crack'
gem 'daemons', :git => 'https://github.com/DouglasAllen/daemons.git'
gem 'data_objects', :git => 'https://github.com/DouglasAllen/do.git'
gem 'domain_name', :git => 'https://github.com/DouglasAllen/ruby-domain_name.git'
gem 'dm-core', :git => 'https://github.com/DouglasAllen/dm-core.git'
gem 'dm-do-adapter', :git => 'https://github.com/DouglasAllen/dm-do-adapter.git'
gem 'dm-migrations', :git => 'https://github.com/DouglasAllen/dm-migrations.git'
gem 'dm-sqlite-adapter', :git => 'https://github.com/DouglasAllen/dm-sqlite-adapter.git'
gem 'do_sqlite3'
gem 'equationoftime', :git => 'https://github.com/DouglasAllen/equationoftime.git'
gem 'eventmachine', :git => 'https://github.com/DouglasAllen/eventmachine.git'
gem 'execjs', :git => 'https://github.com/DouglasAllen/execjs.git' 
gem 'haml', :git => 'https://github.com/DouglasAllen/haml.git'
gem 'http-cookie',  :git => 'https://github.com/DouglasAllen/http-cookie.git'
gem 'jquery', :git => 'https://github.com/DouglasAllen/jquery-ruby.git'
gem 'json_pure', :git => 'https://github.com/DouglasAllen/json.git'
gem 'liquid', :git => 'https://github.com/DouglasAllen/liquid.git'
gem 'mime-types', :git => 'https://github.com/DouglasAllen/ruby-mime-types.git'
gem 'mini_portile', :git => 'https://github.com/DouglasAllen/mini_portile.git'
gem 'multi_json', :git => 'https://github.com/DouglasAllen/multi_json.git'
gem 'multi_xml', :git => 'https://github.com/DouglasAllen/multi_xml.git'
gem 'netrc', :git => 'https://github.com/DouglasAllen/netrc.git'
gem 'nokogiri', :git => 'https://github.com/DouglasAllen/nokogiri.git'
gem 'rack', :git => 'https://github.com/DouglasAllen/rack.git'
gem 'rack-protection', :git => 'https://github.com/DouglasAllen/rack-protection.git'
gem 'rack-test', :git => 'https://github.com/DouglasAllen/rack-test.git'
gem 'rdiscount', :git => 'https://github.com/DouglasAllen/rdiscount.git'
gem 'rest-client', :git => 'https://github.com/DouglasAllen/rest-client.git'
gem 'safe_yaml', :git => 'https://github.com/DouglasAllen/safe_yaml.git'
gem 'sinatra', :git => 'https://github.com/DouglasAllen/sinatra.git'
gem 'sinatra-contrib', :git => 'https://github.com/DouglasAllen/sinatra-contrib.git'
gem 'sqlite3',:git => 'https://github.com/DouglasAllen/sqlite3-ruby.git'
gem 'thin', :git => 'https://github.com/DouglasAllen/thin.git'
gem 'tilt', :git => 'https://github.com/DouglasAllen/tilt.git'
gem 'unf', :git => 'https://github.com/DouglasAllen/ruby-unf.git'
gem 'unf_ext', :git => 'https://github.com/DouglasAllen/ruby-unf_ext.git'
